version: '3'

services:
  app:
    image: zem/app
    restart: on-failure
    build: .
    expose:
      - 3000
      - 4569
    ports:
      - 3000:3000
      - 4569:4569
    logging:
      options:
        max-size: "1024k"
        max-file: 10